# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94104cde432ee922fbe2a6eb1a08b7795874237f5d743d680fac6a90a98470a75ffc1de7ebeff4c8b833773aa04d41b44b0fca7cfb273a7dcaa86df400e3ffe

test:
  secret_key_base: c50cf3fd1f56ea980c5ed699b96aee5fe11bca453aa58c8c72d2e693715e1217d36e4fdc171a551d786ab2e9176655cb628d6ab7f6b5ad4cf48e567aa7fefc50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
